FROM python:3.8.5

RUN mkdir /code
COPY requirements.txt /code
RUN pip install --upgrade pip && \
    pip install -r /code/requirements.txt

COPY ./src /code
WORKDIR /code

EXPOSE 8000

CMD gunicorn config.wsgi:application --bind 0.0.0.0:8000