version: '3.3'

volumes:
  postgres_data:
  static_value:

services:

  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../schema_design/db_schema.sql:/docker-entrypoint-initdb.d/db.sql
    env_file:
      - ./src/.env
  
  backend:
    build: .
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_value:/code/static
      - ../sqlite_to_postgres/:/code/sqlite_to_postgres
    env_file:
      - ./src/.env
    depends_on:
      - postgres

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static
    depends_on:
      - backend